#!/usr/bin/python

import time
from src.core import TweetDragger

if __name__ == '__main__':
	import argparse

	parser = argparse.ArgumentParser(description='Twitter account scraper and tweet displayer')
	parser.add_argument('account', type=str, help='twitter handle to scrape')
	args = parser.parse_args()

	username = args.account

	dragger = TweetDragger(username)
	dragger.populate()

	# store the most recent tweet so we know where to pick up from
	latestTweet = list(dragger.tweets)[-1]

	dragger.printRecentTweets(5) # print 5 most recent tweets
	print()

	sec = input('input something to continue execution\n')

	# time.sleep(int(sec))

	print('Continuing execution')

	dragger.update()

	dragger.printNewTweetsSince(latestTweet)